version: '3.7'
services:
  dnd-helper:
    build: .
    ports:
      - "4200:4200"
    depends_on:
      - dnd-helper-db

  dnd-helper-db:
    image: surrealdb/surrealdb:latest
    restart: always
    user: root
    command: start --user admin --pass admin rocksdb:/data/database.db
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
  dnd-minio:
    image: minio/minio:latest
    restart: always
    user: root
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ROOTNAME
      MINIO_ROOT_PASSWORD: CHANGEME123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./files:/data
